# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.
# Project
version=0.1.0
group=net.dragonmounts
java_version=21
# Common
minecraft_version=1.21.1
mod_name=Dragon Mounts 2
mod_compact_name=DragonMounts2
mod_authors=
mod_id=neodragonmounts
license=GNU GPLv3
credits=
mod_description=As a sequel to Dragon Mounts, this mod adds over 15 new dragons to your game. In addition to new dragons, the mod adds in new armors and tools for players, Armors for Dragons, Nests that generates in every world, New Dragon breeds, and much more.
minecraft_version_range=[1.21.1, 1.21.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17
# Fabric
fabric_version=0.114.0+1.21.1
fabric_loader_version=0.16.9
modmenu_version=11.0.3
# NeoForge
neoforge_version=21.1.93
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
